### ISSUE TITLE
权限设置不合适

### ISSUE THREAD

**Issue by CUZNIL** [XiTianGame/xitian-plugin#2]
`#插件列表` `#查看插件[指定插件名称]`
这俩个指令都没有检查用户是否是bot主人，会导致倒狗很轻松地获取js插件

**Comment by XiTianGame** [comment]
你可以在管理插件权限设置中剔除非主人的权限，配置文件位于插件目录/config/auth.set.yaml

**Comment by TimeRainStarSky** [comment]
> 你可以在管理插件权限设置中剔除非主人的权限，配置文件位于插件目录/config/auth.set.yaml

grade:
 - master

设置无效，#插件列表 #查看插件[指定插件名称] 仍然是任何人可操作

**Comment by XiTianGame** [comment]
感谢反馈，已经更新修复`09fa06b054e1a5d13ab77e0da1b6e803193ee4f0`

**Comment by XiTianGame** [comment]
感谢反馈，已经更新修复
