### ISSUE TITLE
【issue】安装完毕后出现文字乱码，没有找到相关配置路径

### ISSUE THREAD

**Issue by 358670500** [XiTianGame/xitian-plugin#3]
![6c2ac157b3d80e4336664ec20b3c43e4](https://user-images.githubusercontent.com/33712573/202982303-aabc0c94-9ce0-43ad-93db-6c32162eb14e.jpg)
求大佬指导下，蟹蟹

**Comment by XiTianGame** [comment]
可能是没有安装中文字体环境的问题，这个问题大多出现于linux系统上，可以百度你的系统安装中文字体库的命令进行解决

**Comment by XiTianGame** [comment]
[#850](https://github.com/Le-niao/Yunzai-Bot/issues/850)

**Comment by 358670500** [comment]
问题已解决，多谢大佬
