### ISSUE TITLE
停用和删除功能失效

### ISSUE THREAD

**Issue by jiut** [XiTianGame/xitian-plugin#4]
![SNKD%PJZ84J{3BT)0{65FU0](https://user-images.githubusercontent.com/52725935/212900936-30ff3a25-cd17-4a03-aa4d-d1efb5e0f0a9.jpg)

**Comment by XiTianGame** [comment]
删除插件目录/config/group.set.yaml后重启试试

**Comment by jiut** [comment]
删除该文件或者删除插件再重新安装都不能解决。

但是以前在同一机器上安装的相同机器人是可以运行的。

**Comment by XiTianGame** [comment]
运行的系统是否为linux系统？

**Comment by jiut** [comment]
是ubuntu

**Comment by XiTianGame** [comment]
应该是因为windows和linux路径表示方式不同，之后的更新会去修复，请耐心等待

**Comment by jiut** [comment]
同一机器指的是完全相同的条件，两个的环境是完全相同的，除了一次rm -rf /*。

**Comment by jiut** [comment]
在另一个文件夹重新下载了yunzai再安装插件依然有同样的问题。

**Comment by XiTianGame** [comment]
当然，但遗憾的是我手上并没有linux机器，而且插件在windows系统上通过测试，唯一可能的原因就是两种系统路径差异的问题

**Comment by jiut** [comment]
但是之前也可以在ubuntu运行。

**Comment by XiTianGame** [comment]
已经推送更新，可以尝试更新解决

**Comment by jiut** [comment]
更新之后还是一样

**Comment by XiTianGame** [comment]
我需要确认一下，重命名功能是否正常？只有停用和删除功能失效吗

**Comment by jiut** [comment]
```
[插件管理][rename]
0|Yunzai-B | [YzBot][14:09:53.958][ERRO] Error: ENOENT: no such file or directory, rename 'plugins/example\/openai.js' -> 'plugins/example\/chat.js'
0|Yunzai-B |     at Object.renameSync (node:fs:1026:3)
0|Yunzai-B |     at Manager.rename (file:///home/jiut/Yunzai-Bot/plugins/xitian-plugin/apps/Manager.js:317:8)
0|Yunzai-B |     at runMicrotasks (<anonymous>)
0|Yunzai-B |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
0|Yunzai-B |     at async PluginsLoader.deal (file:///home/jiut/Yunzai-Bot/lib/plugins/loader.js:251:52)
```

**Comment by jiut** [comment]
![image](https://user-images.githubusercontent.com/52725935/213388698-fb18297a-ab32-49ce-b7e7-dfe296baa9f4.png)
现在停用会导致插件列表同时出现停用前和停用后两个插件

**Comment by XiTianGame** [comment]
了解了，好消息是这个插件确实被停用了，晚点再做修复

**Comment by XiTianGame** [comment]
问题是否得到解决？如果已经解决，你可以关闭这个issue
