### ISSUE TITLE
插件列表能否只显示js后缀文件

### ISSUE THREAD

**Issue by chomoe327** [XiTianGame/xitian-plugin#6]
![bc6d0d89b6e3fb2ad22d5ed03f574365](https://user-images.githubusercontent.com/71968682/233815784-128f4895-6fa7-4b21-90cc-d7c3ac295437.gif)
因为有一个插件需要pnpm拉取依赖，在example目录下拉取后出现了node_modules,pnpm-lock等等文件，导致插件列表中把这些也显示了
能否改成只显示js后缀名的插件

**Comment by XiTianGame** [comment]
已增加开关，在group.set中将onlyJS设置为true即可
[7cd5fb1](https://github.com/XiTianGame/xitian-plugin/commit/7cd5fb1122c45b744fa412aef4f9731db16644fd)

**Comment by chomoe327** [comment]
> 已增加开关，在group.set中将onlyJS设置为true即可 [7cd5fb1](https://github.com/XiTianGame/xitian-plugin/commit/7cd5fb1122c45b744fa412aef4f9731db16644fd)

好的谢谢
