### ISSUE TITLE
在trss-yunzai中异常卡死

### ISSUE THREAD

**Issue by yeqiu6080** [XiTianGame/xitian-plugin#7]
![输入图片说明](https://foruda.gitee.com/images/1722838407404518670/320fbac9_7555337.png "屏幕截图")![输入图片说明](https://foruda.gitee.com/images/1722838410728296947/d76cbb50_7555337.png "屏幕截图")完全不响应任何指令

**Comment by XiTianGame** [comment]
安装功能还没适配，如果已经进入安装状态，可以使用`#取消安装插件`退出

**Comment by yeqiu6080** [comment]
但是为什么之前都能正常安装？

**Comment by XiTianGame** [comment]
没有适配trss（理论上trss用icqq也能用）。你用的协议是什么，我回头试着修一下

**Comment by yeqiu6080** [comment]
> 没有适配trss（理论上trss用icqq也能用）。你用的协议是什么，我回头试着修一下

icqq啊
![1e4ad77a593d6bbb9ded6e830d2e46bc_720](https://github.com/user-attachments/assets/13ba6d28-0e86-40a4-94a2-9395d2269b21)

**Comment by yeqiu6080** [comment]
之前都用的好好的
![image](https://github.com/user-attachments/assets/f2251802-1b87-4447-ab82-4451ce6cde10)

**Comment by yeqiu6080** [comment]
之前都用的好好的
![image](https://github.com/user-attachments/assets/539a6b11-3cb4-425c-a474-955adf79933f)

**Comment by XiTianGame** [comment]
![8ae8f470eee54ad745e96ecac03e2eb3](https://github.com/user-attachments/assets/996fc016-718f-42c8-8148-450b80e8cc90)
![dad41f9eecdb0c43371d8616f7648094](https://github.com/user-attachments/assets/36e5aa98-932a-4b73-9d59-ee5f12d5320c)
相同环境已经完成测试，没有任何问题，如果昨天是好的可以想一下这段时间动过什么地方

**Comment by XiTianGame** [comment]
稍微改了下逻辑，如果单次安装发送不正确信息会结束安装

**Comment by yeqiu6080** [comment]
> 稍微改了下逻辑，如果单次安装发送不正确信息会结束安装
请问gitee仓库能不能同步一下？

**Comment by XiTianGame** [comment]
已同步

**Comment by yeqiu6080** [comment]
> 已同步

![image](https://github.com/user-attachments/assets/3eae352e-a7c4-4836-944e-13d44c42b799)

**Comment by XiTianGame** [comment]
用这个命令试试`#更新xitian-plugin`
