### ISSUE TITLE
使用#插件帮助时电脑桌面会出现白屏

### ISSUE THREAD

**Issue by Qyyxzz** [XiTianGame/xitian-plugin#9]
用类似的插件的列表功能貌似都会出现这个问题 大佬有什么头绪吗

**Comment by Qyyxzz** [comment]
![QQ20241006-040949](https://github.com/user-attachments/assets/6aa0b0fc-db01-420d-8cbf-662585f46699)

**Comment by XiTianGame** [comment]
看看这个 yoimiya-kokomi/Miao-Yunzai#476
这个问题之前有人在Miao-Yunzai上提过了

**Comment by Qyyxzz** [comment]
> 看看这个 [yoimiya-kokomi/Miao-Yunzai#476](https://github.com/yoimiya-kokomi/Miao-Yunzai/issues/476) 这个问题之前有人在Miao-Yunzai上提过了

okok 感谢大佬
